"""empty message

Revision ID: 234c16f39663
Revises: f24029775d72
Create Date: 2025-04-15 18:09:45.795827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234c16f39663'
down_revision: Union[str, None] = 'f24029775d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_check', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
