"""empty message

Revision ID: 2be597a503d8
Revises: 03bd79d4a97d
Create Date: 2025-04-27 10:30:23.151789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be597a503d8'
down_revision: Union[str, None] = '03bd79d4a97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'comment')
    # ### end Alembic commands ###
